### ISSUE TITLE
Add a way to report in Cobertura coverage.xml format

### ISSUE THREAD

**Issue by bitle** [edx/diff-cover#134] opened 2015-01-12 22:20 UTC
There are many tools that can parse and render coverage.xml. It would be nice, if diff-cover could generate a Cobertura report.

**Comment by aconrad** [comment] 2015-01-12 22:44
That's what pycobertura was designed for originally.

**Comment by Bachmann1234** [comment] 2015-01-12 23:44
Howdy! 

This has come up before
https://github.com/edx/diff-cover/issues/119

I was unsure about it because I was not sure what a partial Cobertua report looks like. The requestor ended up closing the ticket.

Though I guess there is a fair amount of demand. Feel free to put up a PR with some examples. At some point I can look into this and perhaps spit something out. I supposed you could just display the lines that are in the diff then recompute the percentages.

@aconrad does pycobertura spit out a cobertura when you do a diff? Also kudos, looks like it has grown a ton since I last looked. Pretty impressive :-)

**Comment by aconrad** [comment] 2015-01-13 01:05
I actually misread the @bitle's request: no, pycobertura doesn't generate a new coverage file but it prints the coverage summary of a Cobertura report (similar to coverage.py) using `pycobertura show coverage.xml`.

So is the request to generate a partial Cobertura report that would be the result of the diff? What's the use-case?

@Bachmann1234 thanks! pycobertura grew quite a bit over the holidays (spare time!), and to be honest it grew to the point where it's now overlapping with diff-cover's functionality. I explain here on how each tool differs from one another: https://github.com/SurveyMonkey/pycobertura#isnt-pycobertura-the-same-tool-as-diff-cover. That being said, pycobertura doesn't have anything such as `diff-quality`, it's meant to be coverage centric and language agnostic (yes, the "py" in "pycobertura" doesn't make it sounds like it's language agnostic, haha).

**Comment by Bachmann1234** [comment] 2015-01-13 01:44
@aconrad yep, we certainly have overlap. Diff-cover tries to be language agnostic. I think what is more interesting is how you disconnect from the VCS. Diff-cover should work on any language, but for now at least you do need to be a git repo.

**Comment by aconrad** [comment] 2015-01-13 02:20
Right, I meant that `diff-quality` was too Python centric.

But back to @bitle, sorry for hijacking your thread. Could you explain what you'd expect from the generated Cobertura report?

**Closed** 2015-03-03 17:22 UTC
